site_name: Bases
site_url: https://remideas.github.io/Bases

repo_name: remi-reyes/Documentations
repo_url: https://github.com/remideas/Bases
edit_uri: ""

extra_css:
  - stylesheets/extra.css

theme:
    language: en
    name: material
    palette:
      - scheme: light
        toggle:
            icon: material/lightbulb-outline
            name: Switch to dark mode.
      - scheme: dark
        toggle:
            icon: material/lightbulb
            name: Switch to light mode.
    features:
      - navigation.instant
      - navigation.tabs

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - codehilite:
        use_pygments: true