site_name: Bases
site_url: https://remideas.github.io/Bases

repo_name: remideas/Bases
repo_url: https://github.com/remideas/Bases
edit_uri: ""

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

theme:
    language: en
    name: material
    palette:
      - scheme: light
        toggle:
            icon: material/lightbulb-outline
            name: Switch to dark mode.
      - scheme: dark
        toggle:
            icon: material/lightbulb
            name: Switch to light mode.
    features:
      - navigation.instant
      - navigation.tabs
      - navigation.top

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_div_format
  - admonition
        
nav:
  - index.md
  - getting_started.md